"""
gRPC client for communicating with Synaptix.Backend.Api on port 5001 (HTTP/2).

Usage
-----
The module exposes a single async context manager `get_sidecar_stub()` for
one-off calls, and a long-lived `GrpcClientManager` singleton that is attached
to ``app.state`` during FastAPI's lifespan.

Quick start (one-off call in a router):
    async with get_sidecar_stub() as stub:
        resp = await stub.ReportAnalyticsEvent(req)

Batch streaming (analytics batch sender):
    async with get_sidecar_stub() as stub:
        async def _gen():
            for event in events:
                yield event
        summary = await stub.StreamAnalyticsEvents(_gen())

NOTE
----
Python stubs (sidecar_pb2, sidecar_pb2_grpc) are generated from
``protos/sidecar.proto`` via grpcio-tools.  Run ``bash generate_grpc.sh``
once after cloning or whenever the proto file changes.  The generated files
land in ``app/grpc_generated/``.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
from typing import AsyncIterator

import grpc
import grpc.aio

from app.config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Lazy import of generated stubs (generated by generate_grpc.sh)
# ---------------------------------------------------------------------------
try:
    from app.grpc_generated import sidecar_pb2, sidecar_pb2_grpc  # type: ignore

    _STUBS_AVAILABLE = True
except ImportError:
    _STUBS_AVAILABLE = False
    logger.warning(
        "gRPC stubs not found — run `bash generate_grpc.sh` to generate them. "
        "All gRPC calls will be no-ops until stubs are present."
    )


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

@contextlib.asynccontextmanager
async def get_sidecar_stub() -> AsyncIterator:
    """
    Async context manager that yields a connected ``SidecarServiceStub``.
    Opens a new channel per call — suitable for low-frequency calls.
    For high-throughput paths, use ``GrpcClientManager`` instead.
    """
    if not _STUBS_AVAILABLE:
        yield _NoopStub()
        return

    channel = grpc.aio.insecure_channel(settings.backend_grpc_url)
    try:
        stub = sidecar_pb2_grpc.SidecarServiceStub(channel)
        yield stub
    finally:
        await channel.close()


class GrpcClientManager:
    """
    Long-lived gRPC channel + stub, attached to ``app.state.grpc`` during
    FastAPI's lifespan.  Reuses the channel across requests — more efficient
    for frequent internal calls.

    Attach in main.py lifespan:
        app.state.grpc = GrpcClientManager()
        await app.state.grpc.connect()
        yield
        await app.state.grpc.close()

    Then in a router:
        stub = request.app.state.grpc.stub
        resp = await stub.ReportAnalyticsEvent(req)
    """

    def __init__(self) -> None:
        self._channel: grpc.aio.Channel | None = None
        self.stub = _NoopStub()

    async def connect(self) -> None:
        if not _STUBS_AVAILABLE:
            logger.warning("gRPC stubs unavailable — GrpcClientManager running in no-op mode")
            return
        self._channel = grpc.aio.insecure_channel(
            settings.backend_grpc_url,
            options=[
                ("grpc.keepalive_time_ms", 30_000),
                ("grpc.keepalive_timeout_ms", 10_000),
                ("grpc.keepalive_permit_without_calls", 1),
            ],
        )
        self.stub = sidecar_pb2_grpc.SidecarServiceStub(self._channel)
        logger.info("gRPC channel connected to %s", settings.backend_grpc_url)

    async def close(self) -> None:
        if self._channel is not None:
            await self._channel.close()
            logger.info("gRPC channel closed")


# ---------------------------------------------------------------------------
# Convenience wrappers (used by ml.py / analytics.py routers)
# ---------------------------------------------------------------------------

async def report_event(event_type: str, entity_id: str, payload_json: str = "{}") -> bool:
    """Fire-and-forget analytics event.  Returns True if accepted."""
    if not _STUBS_AVAILABLE:
        return False
    try:
        req = sidecar_pb2.AnalyticsEventRequest(
            event_type=event_type,
            entity_id=entity_id,
            payload_json=payload_json,
        )
        async with get_sidecar_stub() as stub:
            resp = await stub.ReportAnalyticsEvent(req)
            return resp.accepted
    except grpc.aio.AioRpcError as exc:
        logger.error("gRPC ReportAnalyticsEvent failed: %s", exc.details())
        return False


async def submit_inference(model_name: str, entity_id: str, score: float, metadata_json: str = "{}") -> str | None:
    """Submit an ML inference result.  Returns the stored record_id or None."""
    if not _STUBS_AVAILABLE:
        return None
    try:
        req = sidecar_pb2.InferenceResultRequest(
            model_name=model_name,
            entity_id=entity_id,
            score=score,
            metadata_json=metadata_json,
        )
        async with get_sidecar_stub() as stub:
            resp = await stub.SubmitInferenceResult(req)
            return resp.record_id if resp.stored else None
    except grpc.aio.AioRpcError as exc:
        logger.error("gRPC SubmitInferenceResult failed: %s", exc.details())
        return None


# ---------------------------------------------------------------------------
# No-op stub — used when stubs are not yet generated
# ---------------------------------------------------------------------------

class _NoopStub:
    """Silently swallows all RPC calls when stubs are not available."""

    async def ReportAnalyticsEvent(self, *_, **__):
        return _NoopResponse(accepted=False, reject_reason="stubs not generated")

    async def StreamAnalyticsEvents(self, *_, **__):
        return _NoopResponse(events_received=0, events_accepted=0, events_rejected=0)

    async def SubmitInferenceResult(self, *_, **__):
        return _NoopResponse(stored=False)

    async def TriggerBackendAction(self, *_, **__):
        return _NoopResponse(executed=False, error_message="stubs not generated")


class _NoopResponse:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)
