// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Synaptix.Backend.Infrastructure.Persistence;

#nullable disable

namespace Synaptix.Backend.Migrations.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260512150000_AddQuestionStatusColumns")]
    partial class AddQuestionStatusColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
