// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Synaptix.Backend.Infrastructure.Persistence;

#nullable disable

namespace Synaptix.Backend.Migrations.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260418183000_AddQuestionStudyFavoritesAndSessionMode")]
    partial class AddQuestionStudyFavoritesAndSessionMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
