# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidecarServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    SidecarService — called by the Python FastAPI sidecar to communicate with
    the .NET Backend API over gRPC (HTTP/2) on port 5001.

    Design notes
    • Unary RPCs (single request / response) for simple analytics events and
    ML inference results.
    • Client-streaming RPC for bulk analytics ingestion so the sidecar can
    batch-send events in a single connection instead of N HTTP calls.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportAnalyticsEvent = channel.unary_unary(
                '/synaptix.sidecar.SidecarService/ReportAnalyticsEvent',
                request_serializer=sidecar__pb2.AnalyticsEventRequest.SerializeToString,
                response_deserializer=sidecar__pb2.AnalyticsEventResponse.FromString,
                _registered_method=True)
        self.StreamAnalyticsEvents = channel.stream_unary(
                '/synaptix.sidecar.SidecarService/StreamAnalyticsEvents',
                request_serializer=sidecar__pb2.AnalyticsEventRequest.SerializeToString,
                response_deserializer=sidecar__pb2.StreamSummary.FromString,
                _registered_method=True)
        self.SubmitInferenceResult = channel.unary_unary(
                '/synaptix.sidecar.SidecarService/SubmitInferenceResult',
                request_serializer=sidecar__pb2.InferenceResultRequest.SerializeToString,
                response_deserializer=sidecar__pb2.InferenceResultResponse.FromString,
                _registered_method=True)
        self.TriggerBackendAction = channel.unary_unary(
                '/synaptix.sidecar.SidecarService/TriggerBackendAction',
                request_serializer=sidecar__pb2.BackendActionRequest.SerializeToString,
                response_deserializer=sidecar__pb2.BackendActionResponse.FromString,
                _registered_method=True)


class SidecarServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    SidecarService — called by the Python FastAPI sidecar to communicate with
    the .NET Backend API over gRPC (HTTP/2) on port 5001.

    Design notes
    • Unary RPCs (single request / response) for simple analytics events and
    ML inference results.
    • Client-streaming RPC for bulk analytics ingestion so the sidecar can
    batch-send events in a single connection instead of N HTTP calls.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def ReportAnalyticsEvent(self, request, context):
        """Report a single analytics event (pageview, match-end, mission-claim, …)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalyticsEvents(self, request_iterator, context):
        """Stream a batch of analytics events; server replies once with a summary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInferenceResult(self, request, context):
        """Submit an ML inference result (match-quality score, churn risk, …)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerBackendAction(self, request, context):
        """Trigger an internal backend action (e.g. flag a player, update a season stat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportAnalyticsEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAnalyticsEvent,
                    request_deserializer=sidecar__pb2.AnalyticsEventRequest.FromString,
                    response_serializer=sidecar__pb2.AnalyticsEventResponse.SerializeToString,
            ),
            'StreamAnalyticsEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAnalyticsEvents,
                    request_deserializer=sidecar__pb2.AnalyticsEventRequest.FromString,
                    response_serializer=sidecar__pb2.StreamSummary.SerializeToString,
            ),
            'SubmitInferenceResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInferenceResult,
                    request_deserializer=sidecar__pb2.InferenceResultRequest.FromString,
                    response_serializer=sidecar__pb2.InferenceResultResponse.SerializeToString,
            ),
            'TriggerBackendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerBackendAction,
                    request_deserializer=sidecar__pb2.BackendActionRequest.FromString,
                    response_serializer=sidecar__pb2.BackendActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synaptix.sidecar.SidecarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synaptix.sidecar.SidecarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarService(object):
    """─────────────────────────────────────────────────────────────────────────────
    SidecarService — called by the Python FastAPI sidecar to communicate with
    the .NET Backend API over gRPC (HTTP/2) on port 5001.

    Design notes
    • Unary RPCs (single request / response) for simple analytics events and
    ML inference results.
    • Client-streaming RPC for bulk analytics ingestion so the sidecar can
    batch-send events in a single connection instead of N HTTP calls.
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def ReportAnalyticsEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synaptix.sidecar.SidecarService/ReportAnalyticsEvent',
            sidecar__pb2.AnalyticsEventRequest.SerializeToString,
            sidecar__pb2.AnalyticsEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalyticsEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/synaptix.sidecar.SidecarService/StreamAnalyticsEvents',
            sidecar__pb2.AnalyticsEventRequest.SerializeToString,
            sidecar__pb2.StreamSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInferenceResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synaptix.sidecar.SidecarService/SubmitInferenceResult',
            sidecar__pb2.InferenceResultRequest.SerializeToString,
            sidecar__pb2.InferenceResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerBackendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synaptix.sidecar.SidecarService/TriggerBackendAction',
            sidecar__pb2.BackendActionRequest.SerializeToString,
            sidecar__pb2.BackendActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
