#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  CREATE EXTENSION IF NOT EXISTS "pg_trgm";
  CREATE EXTENSION IF NOT EXISTS "btree_gin";

  CREATE SCHEMA IF NOT EXISTS game;
  CREATE SCHEMA IF NOT EXISTS user_management;
  CREATE SCHEMA IF NOT EXISTS analytics;

  GRANT ALL PRIVILEGES ON SCHEMA game TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON SCHEMA user_management TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON SCHEMA analytics TO "$POSTGRES_USER";
EOSQL

echo "PostgreSQL initialization completed successfully!"
