from django.urls import path

from .views import (
    admin_permissions_view,
    anticheat_flag_review,
    anticheat_flags_view,
    anticheat_party_flag_review,
    anticheat_party_flags_view,
    backend_installer_upload,
    backend_installer_validate,
    backend_installer_view,
    dashboard_home,
    economy_balance_view,
    economy_grant,
    economy_player_view,
    escalations_view,
    event_queue_reprocess,
    event_queue_view,
    feature_flags_view,
    forgot_password_view,
    game_event_close,
    game_event_open,
    game_event_start,
    game_events_view,
    geo_lookup_view,
    healthz,
    login_view,
    logout_view,
    matches_view,
    minio_diagnostics_view,
    mongodb_collection_detail_view,
    mongodb_status_view,
    notifications_channel_upsert,
    notifications_dead_letter_replay,
    notifications_schedule,
    notifications_scheduled_cancel,
    notifications_send,
    notifications_template_create,
    notifications_template_delete,
    notifications_template_update,
    notifications_view,
    operator_audit_security,
    operator_audit_security_detail_view,
    operator_audit_security_view,
    operator_health,
    operator_media_intent,
    operator_media_intent_view,
    operator_minio_diagnostics,
    operator_moderation_log_detail_view,
    operator_moderation_logs,
    operator_moderation_logs_view,
    operator_moderation_player_view,
    operator_moderation_profile,
    operator_moderation_set_status,
    operator_mongodb_status,
    operator_setup_history,
    operator_setup_readiness,
    operator_setup_seeds,
    operator_setup_services,
    operator_setup_status,
    operator_setup_validation,
    operator_user_activity,
    operator_user_ban,
    operator_user_detail,
    operator_user_detail_view,
    operator_user_investigation_view,
    operator_user_unban,
    operator_user_update,
    operator_users,
    operator_users_view,
    personalization_overview_view,
    personalization_player_recalculate,
    personalization_player_reset,
    personalization_player_view,
    personalization_rule_upsert,
    personalization_rules_view,
    player_resolve_view,
    player_transaction_dispute,
    player_transaction_reverse,
    player_transactions_view,
    powerups_view,
    probe_log_view,
    question_create_view,
    question_delete,
    question_detail_view,
    questions_approve,
    questions_bulk_import_view,
    questions_queue_view,
    questions_reject,
    reset_password_view,
    season_points_apply,
    season_points_view,
    seasons_activate,
    seasons_close,
    seasons_leaderboard,
    seasons_recompute,
    seasons_reward_claims_view,
    seasons_view,
    setup_history_view,
    setup_readiness_view,
    setup_seeds_view,
    setup_services_view,
    setup_status_view,
    setup_validation_view,
    skills_view,
    storage_object_detail_view,
    storage_objects_view,
    storage_upload_view,
    store_analytics_view,
    store_catalog_detail_view,
    store_catalog_new_view,
    store_catalog_view,
    store_flash_sale_cancel,
    store_flash_sale_edit_view,
    store_flash_sale_schedule_view,
    store_flash_sales_view,
    store_player_stock_override,
    store_player_stock_view,
    store_reward_limit_detail_view,
    store_reward_limits_view,
    store_stock_policies_bulk_reset,
    store_stock_policies_view,
    store_stock_policy_detail_view,
    store_stock_policy_new_view,
)

urlpatterns = [
    path("", dashboard_home, name="dashboard-home"),
    path("login", login_view, name="operator-login"),
    path("logout", logout_view, name="operator-logout"),
    path("forgot-password", forgot_password_view, name="operator-forgot-password"),
    path("reset-password", reset_password_view, name="operator-reset-password"),
    path("api/operator/health", operator_health, name="operator-health"),
    path("api/operator/setup/status", operator_setup_status, name="operator-setup-status"),
    path("api/operator/setup/readiness", operator_setup_readiness, name="operator-setup-readiness"),
    path("api/operator/setup/services", operator_setup_services, name="operator-setup-services"),
    path("api/operator/setup/seeds", operator_setup_seeds, name="operator-setup-seeds"),
    path("api/operator/setup/validation", operator_setup_validation, name="operator-setup-validation"),
    path("api/operator/setup/history", operator_setup_history, name="operator-setup-history"),
    path("settings/setup", setup_status_view, name="setup-status-view"),
    path("settings/setup/readiness", setup_readiness_view, name="setup-readiness-view"),
    path("settings/setup/services", setup_services_view, name="setup-services-view"),
    path("settings/setup/seeds", setup_seeds_view, name="setup-seeds-view"),
    path("settings/setup/validation", setup_validation_view, name="setup-validation-view"),
    path("settings/setup/history", setup_history_view, name="setup-history-view"),
    path("api/operator/audit/security", operator_audit_security, name="operator-audit-security"),
    path("audit/security", operator_audit_security_view, name="operator-audit-security-view"),
    path("audit/security/<str:event_id>", operator_audit_security_detail_view, name="operator-audit-security-detail-view"),
    path("api/operator/media/intent", operator_media_intent, name="operator-media-intent"),
    path("media/intent", operator_media_intent_view, name="operator-media-intent-view"),
    path("api/operator/minio/diagnostics", operator_minio_diagnostics, name="operator-minio-diagnostics"),
    path("minio/diagnostics", minio_diagnostics_view, name="operator-minio-diagnostics-view"),
    path("api/operator/mongodb/status", operator_mongodb_status, name="operator-mongodb-status"),
    path("mongodb/status", mongodb_status_view, name="operator-mongodb-status-view"),
    path("mongodb/status/<str:database>/<str:collection>", mongodb_collection_detail_view, name="operator-mongodb-collection-detail-view"),
    path("installer", backend_installer_view, name="backend-installer-view"),
    path("installer/validate", backend_installer_validate, name="backend-installer-validate"),
    path("installer/upload", backend_installer_upload, name="backend-installer-upload"),
    path("storage/objects", storage_objects_view, name="storage-objects-view"),
    path("storage/objects/<str:encoded_key>", storage_object_detail_view, name="storage-object-detail-view"),
    path("storage/upload", storage_upload_view, name="storage-upload-view"),
    path("config/admin-permissions", admin_permissions_view, name="admin-permissions-view"),
    path("api/operator/moderation/logs", operator_moderation_logs, name="operator-moderation-logs"),
    path("moderation/logs", operator_moderation_logs_view, name="operator-moderation-logs-view"),
    path("moderation/logs/<str:log_id>", operator_moderation_log_detail_view, name="operator-moderation-log-detail-view"),
    path("moderation/players/<str:player_id>", operator_moderation_player_view, name="operator-moderation-player-view"),
    path("api/operator/moderation/profile/<str:player_id>", operator_moderation_profile, name="operator-moderation-profile"),
    path("api/operator/moderation/set-status", operator_moderation_set_status, name="operator-moderation-set-status"),
    path("api/operator/users", operator_users, name="operator-users"),
    path("players/resolve", player_resolve_view, name="player-resolve-view"),
    path("users", operator_users_view, name="operator-users-view"),
    path("users/<str:user_id>", operator_user_detail_view, name="operator-user-detail-view"),
    path("users/<str:user_id>/investigation", operator_user_investigation_view, name="operator-user-investigation-view"),
    path("api/operator/users/<str:user_id>", operator_user_detail, name="operator-user-detail"),
    path("api/operator/users/<str:user_id>/activity", operator_user_activity, name="operator-user-activity"),
    path("api/operator/users/<str:user_id>/update", operator_user_update, name="operator-user-update"),
    path("api/operator/users/<str:user_id>/ban", operator_user_ban, name="operator-user-ban"),
    path("api/operator/users/<str:user_id>/unban", operator_user_unban, name="operator-user-unban"),
    # Store
    path("store/flash-sales", store_flash_sales_view, name="store-flash-sales-view"),
    path("store/flash-sales/schedule", store_flash_sale_schedule_view, name="store-flash-sale-schedule"),
    path("store/flash-sales/<str:sale_id>/edit", store_flash_sale_edit_view, name="store-flash-sale-edit"),
    path("store/flash-sales/<str:sale_id>/cancel", store_flash_sale_cancel, name="store-flash-sale-cancel"),
    path("store/stock-policies", store_stock_policies_view, name="store-stock-policies-view"),
    path("store/stock-policies/bulk-reset", store_stock_policies_bulk_reset, name="store-stock-policies-bulk-reset"),
    path("store/stock-policies/new", store_stock_policy_new_view, name="store-stock-policy-new"),
    path("store/stock-policies/<str:sku>", store_stock_policy_detail_view, name="store-stock-policy-detail"),
    path("store/player-stock", store_player_stock_view, name="store-player-stock-view"),
    path("store/player-stock/<str:player_id>/override", store_player_stock_override, name="store-player-stock-override"),
    path("store/analytics", store_analytics_view, name="store-analytics-view"),
    path("store/catalog", store_catalog_view, name="store-catalog-view"),
    path("store/catalog/new", store_catalog_new_view, name="store-catalog-new"),
    path("store/catalog/<str:item_id>", store_catalog_detail_view, name="store-catalog-detail"),
    path("store/reward-limits", store_reward_limits_view, name="store-reward-limits-view"),
    path("store/reward-limits/<str:reward_id>", store_reward_limit_detail_view, name="store-reward-limit-detail"),
    # Questions
    path("content/questions", questions_queue_view, name="questions-queue-view"),
    path("content/questions/new", question_create_view, name="question-create-view"),
    path("content/questions/bulk-import", questions_bulk_import_view, name="questions-bulk-import-view"),
    path("content/questions/<str:question_id>", question_detail_view, name="question-detail-view"),
    path("content/questions/<str:question_id>/delete", question_delete, name="question-delete"),
    path("content/questions/<str:question_id>/approve", questions_approve, name="questions-approve"),
    path("content/questions/<str:question_id>/reject", questions_reject, name="questions-reject"),
    # Economy
    path("economy/player", economy_player_view, name="economy-player-view"),
    path("economy/balance", economy_balance_view, name="economy-balance-view"),
    path("economy/grant", economy_grant, name="economy-grant"),
    # Events
    path("events/game-events", game_events_view, name="game-events-view"),
    path("events/game-events/<str:event_id>/open", game_event_open, name="game-event-open"),
    path("events/game-events/<str:event_id>/start", game_event_start, name="game-event-start"),
    path("events/game-events/<str:event_id>/close", game_event_close, name="game-event-close"),
    # Anti-Cheat
    path("security/anticheat", anticheat_flags_view, name="anticheat-flags-view"),
    path("security/anticheat/<str:flag_id>/review", anticheat_flag_review, name="anticheat-flag-review"),
    path("security/anticheat/party", anticheat_party_flags_view, name="anticheat-party-flags-view"),
    path("security/anticheat/party/<str:flag_id>/review", anticheat_party_flag_review, name="anticheat-party-flag-review"),
    # Seasons
    path("operations/seasons", seasons_view, name="seasons-view"),
    path("operations/seasons/reward-claims", seasons_reward_claims_view, name="seasons-reward-claims"),
    path("operations/seasons/<str:season_id>/leaderboard", seasons_leaderboard, name="seasons-leaderboard"),
    path("operations/seasons/activate", seasons_activate, name="seasons-activate"),
    path("operations/seasons/close", seasons_close, name="seasons-close"),
    path("operations/seasons/<str:season_id>/recompute", seasons_recompute, name="seasons-recompute"),
    # Notifications
    path("operations/notifications", notifications_view, name="notifications-view"),
    path("operations/notifications/send", notifications_send, name="notifications-send"),
    path("operations/notifications/schedule", notifications_schedule, name="notifications-schedule"),
    path("operations/notifications/scheduled/<str:schedule_id>/cancel", notifications_scheduled_cancel, name="notifications-scheduled-cancel"),
    path("operations/notifications/channels/upsert", notifications_channel_upsert, name="notifications-channel-upsert"),
    path("operations/notifications/templates/create", notifications_template_create, name="notifications-template-create"),
    path("operations/notifications/templates/<str:template_id>/update", notifications_template_update, name="notifications-template-update"),
    path("operations/notifications/templates/<str:template_id>/delete", notifications_template_delete, name="notifications-template-delete"),
    path("operations/notifications/dead-letter/<str:schedule_id>/replay", notifications_dead_letter_replay, name="notifications-dead-letter-replay"),
    # Event Queue
    path("operations/event-queue", event_queue_view, name="event-queue-view"),
    path("operations/event-queue/reprocess", event_queue_reprocess, name="event-queue-reprocess"),
    # Personalization
    path("personalization", personalization_overview_view, name="personalization-overview-view"),
    path("personalization/player", personalization_player_view, name="personalization-player-view"),
    path("personalization/player/<str:player_id>/recalculate", personalization_player_recalculate, name="personalization-player-recalculate"),
    path("personalization/player/<str:player_id>/reset", personalization_player_reset, name="personalization-player-reset"),
    path("personalization/rules", personalization_rules_view, name="personalization-rules-view"),
    path("personalization/rules/<str:rule_key>/upsert", personalization_rule_upsert, name="personalization-rule-upsert"),
    path("healthz", healthz, name="dashboard-healthz"),
    # Service probe history log
    path("probe-log/<str:service_slug>/", probe_log_view, name="probe-log"),
    # Geo lookup (server-side proxy to ip-api.com — keeps audited IP out of browser)
    path("audit/security/geo-lookup/", geo_lookup_view, name="audit-geo-lookup"),
    # Powerups
    path("economy/powerups", powerups_view, name="powerups-view"),
    # Skills
    path("economy/skills", skills_view, name="skills-view"),
    # Matches
    path("events/matches", matches_view, name="matches-view"),
    # Config
    path("config/feature-flags", feature_flags_view, name="feature-flags-view"),
    # Escalations
    path("moderation/escalations", escalations_view, name="escalations-view"),
    # Player Transactions
    path("economy/player-transactions", player_transactions_view, name="player-transactions-view"),
    path("economy/player-transactions/<str:txn_id>/dispute", player_transaction_dispute, name="player-transaction-dispute"),
    path("economy/player-transactions/<str:txn_id>/reverse", player_transaction_reverse, name="player-transaction-reverse"),
    # Season Points
    path("operations/season-points", season_points_view, name="season-points-view"),
    path("operations/season-points/apply", season_points_apply, name="season-points-apply"),
]
