# Generated by Django 5.2.1 on 2026-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_saved_view_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('latency_ms', models.IntegerField()),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'operator_probe_check_records',
                'ordering': ['-checked_at'],
            },
        ),
    ]
