# Generated by Django 5.2.1 on 2026-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_probe_check_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsavedview',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='operatorsavedview',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='operatorsavedview',
            name='owner_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='operatorsavedviewauditevent',
            name='action',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='operatorsavedviewauditevent',
            name='actor_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='operatorsavedviewauditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='operatorsavedviewauditevent',
            name='owner_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='operatorsavedviewauditevent',
            name='view_name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='probecheckrecord',
            name='service_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='probecheckrecord',
            name='status',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='operatorsavedview',
            index=models.Index(fields=['owner_email', 'is_archived'], name='operator_sa_owner_e_f93566_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsavedview',
            index=models.Index(fields=['is_shared', 'is_archived'], name='operator_sa_is_shar_0c761f_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsavedviewauditevent',
            index=models.Index(fields=['created_at', 'actor_email'], name='operator_sa_created_6e161e_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsavedviewauditevent',
            index=models.Index(fields=['created_at', 'owner_email'], name='operator_sa_created_dc8f30_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsavedviewauditevent',
            index=models.Index(fields=['-created_at'], name='operator_sa_created_bac41c_idx'),
        ),
        migrations.AddIndex(
            model_name='probecheckrecord',
            index=models.Index(fields=['service_name', 'checked_at'], name='operator_pr_service_ced8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='probecheckrecord',
            index=models.Index(fields=['service_name', '-checked_at'], name='operator_pr_service_40a36d_idx'),
        ),
        migrations.AddIndex(
            model_name='probecheckrecord',
            index=models.Index(fields=['status', 'checked_at'], name='operator_pr_status_f5e0ac_idx'),
        ),
    ]
