import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Filter bar for users list
 */
// import React from 'react'
import { Button } from '@/components/ui/button';
export function FilterBar({ filters, onFiltersChange, onClearFilters }) {
    return (_jsxs("div", { className: "space-y-4 p-4 bg-bg-secondary rounded border border-panel-border", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "email-filter", className: "block text-sm font-medium text-ink-primary mb-1", children: "Email" }), _jsx("input", { id: "email-filter", type: "text", placeholder: "Search email...", value: filters.email || '', onChange: (e) => onFiltersChange({ email: e.target.value }), className: "w-full px-3 py-2 border border-panel-border rounded focus-ring text-sm" })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "status-filter", className: "block text-sm font-medium text-ink-primary mb-1", children: "Status" }), _jsxs("select", { id: "status-filter", value: filters.status || '', onChange: (e) => onFiltersChange({ status: e.target.value || undefined }), className: "w-full px-3 py-2 border border-panel-border rounded focus-ring text-sm", children: [_jsx("option", { value: "", children: "All Statuses" }), _jsx("option", { value: "active", children: "Active" }), _jsx("option", { value: "suspended", children: "Suspended" }), _jsx("option", { value: "banned", children: "Banned" }), _jsx("option", { value: "inactive", children: "Inactive" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "flagged-filter", className: "block text-sm font-medium text-ink-primary mb-1", children: "Flagged" }), _jsxs("select", { id: "flagged-filter", value: filters.flagged ? 'true' : 'false', onChange: (e) => onFiltersChange({ flagged: e.target.value === 'true' || undefined }), className: "w-full px-3 py-2 border border-panel-border rounded focus-ring text-sm", children: [_jsx("option", { value: "false", children: "All" }), _jsx("option", { value: "true", children: "Flagged Only" })] })] })] }), _jsx("div", { className: "flex gap-2", children: _jsx(Button, { variant: "secondary", size: "sm", onClick: onClearFilters, children: "Clear Filters" }) })] }));
}
