// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tycoon.Backend.Infrastructure.Persistence;

#nullable disable

namespace Tycoon.Backend.Migrations.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260321090000_AddGameBalancePolicyPersistence")]
    partial class AddGameBalancePolicyPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal designer – Up/Down contain the full DDL.
            // The authoritative model snapshot is in AppDbModelSnapshot.cs.
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
