// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tycoon.Backend.Infrastructure.Persistence;

#nullable disable

namespace Tycoon.Backend.Migrations.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260509120000_AddDailyAndWeeklyRewards")]
    partial class AddDailyAndWeeklyRewards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
