import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const STATUS_CONFIG = {
    active: { color: 'bg-status-healthy/10 text-status-healthy border-status-healthy', label: 'Active' },
    suspended: { color: 'bg-status-degraded/10 text-status-degraded border-status-degraded', label: 'Suspended' },
    banned: { color: 'bg-status-offline/10 text-status-offline border-status-offline', label: 'Banned' },
    inactive: { color: 'bg-ink-tertiary/10 text-ink-tertiary border-ink-tertiary', label: 'Inactive' },
};
export function PlayerHeader({ profile, isLoading }) {
    if (isLoading) {
        return (_jsxs("div", { className: "operator-card space-y-4", children: [_jsx("div", { className: "h-12 bg-bg-secondary rounded animate-pulse" }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-5 gap-3", children: [...Array(5)].map((_, i) => (_jsx("div", { className: "h-16 bg-bg-secondary rounded animate-pulse" }, i))) })] }));
    }
    const config = STATUS_CONFIG[profile.status];
    const trustScoreColor = profile.trustScore >= 80 ? 'text-status-healthy' : profile.trustScore >= 50 ? 'text-status-degraded' : 'text-status-offline';
    return (_jsxs("div", { className: "operator-card space-y-6", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-ink-primary", children: profile.handle }), _jsx("p", { className: "text-sm text-ink-secondary mt-1", children: profile.email })] }), _jsx("span", { className: `px-4 py-2 rounded-lg border-2 font-semibold text-sm ${config.color}`, children: config.label })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-5 gap-4 pt-4 border-t border-panel-border", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Account Created" }), _jsx("p", { className: "text-sm font-medium text-ink-primary mt-1", children: new Date(profile.createdAt).toLocaleDateString() })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Last Active" }), _jsx("p", { className: "text-sm font-medium text-ink-primary mt-1", children: profile.lastActiveAt ? new Date(profile.lastActiveAt).toLocaleDateString() : 'Never' })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Flags" }), _jsx("p", { className: `text-lg font-bold mt-1 ${profile.flagCount > 0 ? 'text-status-offline' : 'text-status-healthy'}`, children: profile.flagCount })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Playtime" }), _jsxs("p", { className: "text-sm font-medium text-ink-primary mt-1", children: [profile.playtimeHours, "h"] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Trust Score" }), _jsxs("p", { className: `text-lg font-bold mt-1 ${trustScoreColor}`, children: [Math.round(profile.trustScore), "%"] })] })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-3 gap-4 pt-4 border-t border-panel-border", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Balance" }), _jsx("p", { className: "text-lg font-bold text-accent mt-1", children: profile.accountBalance.toLocaleString() })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Total Spent" }), _jsx("p", { className: "text-sm font-medium text-ink-secondary mt-1", children: profile.totalSpent.toLocaleString() })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Win Rate" }), _jsxs("p", { className: "text-sm font-medium text-ink-primary mt-1", children: [profile.winRate.toFixed(1), "%"] })] })] })] }));
}
