import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function EconomySummary({ economy, isLoading }) {
    if (isLoading) {
        return (_jsx("div", { className: "operator-card space-y-3", children: [...Array(3)].map((_, i) => (_jsx("div", { className: "h-16 bg-bg-secondary rounded animate-pulse" }, i))) }));
    }
    if (!economy) {
        return null;
    }
    const netEarnings = economy.totalEarned - economy.totalSpent;
    return (_jsxs("div", { className: "operator-card space-y-6", children: [_jsxs("div", { className: "pb-6 border-b border-panel-border", children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Current Balance" }), _jsx("p", { className: "text-4xl font-bold text-accent mt-2", children: economy.currentBalance.toLocaleString() })] }), _jsxs("div", { className: "grid grid-cols-3 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Total Earned" }), _jsxs("p", { className: "text-lg font-bold text-status-healthy mt-1", children: ["+", economy.totalEarned.toLocaleString()] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Total Spent" }), _jsxs("p", { className: "text-lg font-bold text-status-offline mt-1", children: ["-", economy.totalSpent.toLocaleString()] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-ink-tertiary", children: "Net" }), _jsxs("p", { className: `text-lg font-bold mt-1 ${netEarnings >= 0 ? 'text-status-healthy' : 'text-status-offline'}`, children: [netEarnings >= 0 ? '+' : '', netEarnings.toLocaleString()] })] })] }), _jsxs("div", { className: "pt-4 border-t border-panel-border space-y-2", children: [economy.totalRefunded > 0 && (_jsxs("p", { className: "text-sm text-ink-secondary", children: ["Total Refunded: ", economy.totalRefunded.toLocaleString()] })), _jsxs("p", { className: "text-xs text-ink-tertiary", children: ["Account Created: ", new Date(economy.accountCreatedAt).toLocaleDateString()] }), economy.lastTransactionAt && (_jsxs("p", { className: "text-xs text-ink-tertiary", children: ["Last Transaction: ", new Date(economy.lastTransactionAt).toLocaleDateString()] }))] })] }));
}
